

name: "autoIssues"
on:
  issues:
    types: [labeled, unlabeled, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: auto issues list in json
        uses: kangyana/issues-to-json@master
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          labels: "javascript,react,webpack"
          state: "open"
          creator: "kangyana"
          per_page: 100
          sort: "created"
          direction: "asc"
      - name: build docs
        run: yarn doc
      - name: add-and-commit
        uses: EndBug/add-and-commit@v4
        with:
          message: issues.json has been re-written
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}